# Generated by Django 4.0.5 on 2022-06-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
